### ISSUE TITLE
"No Valid Image Files" Error While Uploading Images to CustomVision From Python SDK

### ISSUE THREAD

**Issue by Curiouspaul1** [microsoft/studentambassadors#171]
## Describe the bug
After following the steps in the [cv-classify-bird-species](https://learn.microsoft.com/en-us/training/modules/cv-classify-bird-species/3a-upload-images) module, i tried to upload training data (image files) to a customvision project but it fails repeatedly (each time i re-tried) and gives the error:

```bash
Traceback (most recent call last):
  File "app.py", line 59, in <module>
    uploadImageList(batch)
  File "app.py", line 42, in uploadImageList
    upload_result = trainer.create_images_from_files(project_id="38b1f962-a7dc-4c64-9ccb-d378e873c7d3", batch=image_list)
  File "C:\Users\Paulo\documents\projects\customv\env\lib\site-packages\azure\cognitiveservices\vision\customvision\training\operations\_custom_vision_training_client_operations.py", line 970, in create_images_from_files
    raise models.CustomVisionErrorException(self._deserialize, response)
azure.cognitiveservices.vision.customvision.training.models._models_py3.CustomVisionErrorException: No valid image files
```
I did some research and found that this issue might be related to an open issue on the repo for the python SDK [#here](https://github.com/Azure/azure-sdk-for-python/issues/17734). Which i believe might be same cause for this issue.

## To Reproduce
1. Go to https://learn.microsoft.com/en-us/training/modules/cv-classify-bird-species
2. Follow the Steps and make sure to install python dependencies.
3. Try running the script to upload the files in the [upload the data](https://learn.microsoft.com/en-us/training/modules/cv-classify-bird-species/3a-upload-images) section.

## Expected behavior
All files are uploaded to custom vision and a success message is returned.

## Screenshots

![image](https://user-images.githubusercontent.com/45743339/225053333-66e6f967-b355-4d53-a2b5-314e3ae5e10a.png)

### Desktop (please complete the following information):
 - OS: Windows
 - Chrome

### Smartphone (please complete the following information):
 - Version 111.0.5563.64 (Official Build) (64-bit)

## Additional context
Issue might be related to [#this](https://github.com/Azure/azure-sdk-for-python/issues/17734)

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.

** Beta Student Ambassador**

***

**Comment by BethanyJep** [comment]
Thank you for this, I'll recreate the process and see how a fix can be applied
